package yukifuri.script.compiler.ast.base

enum class Operator(
    val priority: Int,
    val op: String,
) {
    Assign(0, "="),
    AddAssign(0, "+="),
    SubAssign(0, "-="),
    MulAssign(0, "*="),
    DivAssign(0, "/="),
    ModAssign(0, "%="),
    Add(1, "+"),
    Sub(1, "-"),
    Mul(2, "*"),
    Div(2, "/"),
    Mod(2, "%"),
    Lt(3, "<"),
    Lte(3, "<="),
    Gt(3, ">"),
    Gte(3, ">="),
    Eq(3, "=="),
    Neq(3, "!="),
    And(4, "&&"),
    Or(4, "||"),
    Lsh(5, "<<"),
    Rsh(5, ">>"),
    LogicalAnd(6, "&&"),
    LogicalOr(6, "||"),
    Not(7, "!"),
    Inc(8, "++"),
    Dec(8, "--"),
}
